#!/bin/bash
#create user
USERNAME_PARM="-uname"
USERNAME=""
PASSWORD_PARM="-upwd"
PASSWORD=""

ShowCreateUserExample()
{
  echo -e "Create User example:\n\033[31;49;5;1m bash oat_create_user -uname USERNAME -upwd PASSWORD\033[0m"
}

# Check that the number of params is correct
if [ $# -lt 4 ] || [ $1 != $USERNAME_PARM ] || [ $3 != $PASSWORD_PARM ];then
  echo "parm error!"
  ShowCreateUserExample
  exit 0
fi

USERNAME="$2"
PASSWORD="$4"

# create the user
bash oat_user -a -h node-110 '{"Username":"'$USERNAME'","Password":"'$PASSWORD'"}'
if [ $? == 0 ]; then
  # add the Attest permission to the user for all the existing values
  bash oat_user_permission -a -h node-110 '{"Username":"'$USERNAME'","Class":"Host","Operation":"Attest","ParName":"HostName","Value":".*"}'
  if [ $? == 0 ]; then
    # add the Read_Attest permission to the user only for himself
    bash oat_user_permission -a -h node-110 '{"Username":"'$USERNAME'","Class":"Host","Operation":"Read_Attest","ParName":"Username","Value":"'$USERNAME'"}'
    if [ $? == 0 ]; then
      # add the Read_Report permission to the user for all the existing values
      bash oat_user_permission -a -h node-110 '{"Username":"'$USERNAME'","Class":"Host","Operation":"Read_Report","ParName":"HostName","Value":".*"}'
      if [ $? == 0 ]; then
        # add the User-Edit-Username permission to the user only for himself
        bash oat_user_permission -a -h node-110 '{"Username":"'$USERNAME'","Class":"User","Operation":"Edit","ParName":"Username","Value":"'$USERNAME'"}'
        if [ $? == 0 ]; then
          # add the User-Edit-Username permission to the user only for alphanumeric values
          bash oat_user_permission -a -h node-110 '{"Username":"'$USERNAME'","Class":"User","Operation":"Edit","ParName":"Password","Value":"[a-zA-z0-9]+"}'
          if [ $? != 0 ]; then
            echo -e "oat_user_permission -a User-Edit-Password failed!"
          fi
        else
          echo -e "oat_user_permission -a User-Edit-Username failed!"
        fi
      else
        echo -e "oat_user_permission -a Read_Report failed!"
      fi
    else
      echo -e "oat_user_permission -a Read_Attest failed!"
    fi
  else
    echo -e "oat_user_permission -a Attest failed!"
  fi
else
  echo -e "oat_user -a failed!"
fi