#!/bin/bash
#create user-manager user
USERNAME_PARM="-uname"
USERNAME=""
PASSWORD_PARM="-upwd"
PASSWORD=""

ShowCreateUserExample()
{
  echo -e "Create User example:\n\033[31;49;5;1m bash oat_create_usermanager_user -uname USERNAME -upwd PASSWORD\033[0m"
}

# Check that the number of params is correct
if [ $# -lt 4 ] || [ $1 != $USERNAME_PARM ] || [ $3 != $PASSWORD_PARM ];then
  echo "parm error!"
  ShowCreateUserExample
  exit 0
fi

USERNAME="$2"
PASSWORD="$4"

# create the user
bash oat_user -a -h node-110 '{"Username":"'$USERNAME'","Password":"'$PASSWORD'"}'
if [ $? == 0 ]; then
  # add the User-Add-Username permission to the user for all the existing values
  bash oat_user_permission -a -h node-110 '{"Username":"'$USERNAME'","Class":"User","Operation":"Add","ParName":"Username","Value":".*"}'
  if [ $? == 0 ]; then
    # add the User-Add-Password permission to the user only for alphanumeric values
    bash oat_user_permission -a -h node-110 '{"Username":"'$USERNAME'","Class":"User","Operation":"Add","ParName":"Password","Value":"[a-zA-z0-9]+"}'
    if [ $? == 0 ]; then
      # add the User-Edit-Username permission to the user for all the existing values
      bash oat_user_permission -a -h node-110 '{"Username":"'$USERNAME'","Class":"User","Operation":"Edit","ParName":"Username","Value":".*"}'
      if [ $? == 0 ]; then
        # add the User-Edit-Username permission to the user only for alphanumeric values
        bash oat_user_permission -a -h node-110 '{"Username":"'$USERNAME'","Class":"User","Operation":"Edit","ParName":"Password","Value":"[a-zA-z0-9]+"}'
        if [ $? == 0 ]; then
          # add the User-Delete-Username permission to the user for all the existing values
          bash oat_user_permission -a -h node-110 '{"Username":"'$USERNAME'","Class":"User","Operation":"Delete","ParName":"Username","Value":".*"}'
          if [ $? != 0 ]; then
            echo -e "oat_user_permission -a User-Edit-Password failed!"
          fi
        else
          echo -e "oat_user_permission -a User-Edit-Username failed!"
        fi
      else
        echo -e "oat_user_permission -a Read_Report failed!"
      fi
    else
      echo -e "oat_user_permission -a Read_Attest failed!"
    fi
  else
    echo -e "oat_user_permission -a Attest failed!"
  fi
else
  echo -e "oat_user -a failed!"
fi